name: Publish & Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    name: GoIM
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Get Tag
        id: get_tag
        run: |
          echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Set Up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build With Gradle
        run: |
        chmod +x gradlew
        ./gradlew buildCiRelease -PVERSION_NAME=${{ steps.get_tag.outputs.TAG }} -PVERSION_CODE=${{ steps.get_tag.outputs.TAG }} -PAPK_NAME=glide_im_release_${{ steps.get_tag.outputs.TAG }}.apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GitAction }}
        with:
          tag_name: ${{ github.ref }}
          release_name: GlideIM_release_${{ steps.get_tag.outputs.TAG }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GitAction }}
        with:
          tag_name: ${{ github.ref }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: glide_im_release_${{ steps.get_tag.outputs.TAG }}.apk
          asset_name: glide_im_release_${{ steps.get_tag.outputs.TAG }}.apk
          asset_content_type: application/gzip
